language: ruby
rvm:
  - 2.4.0
before_install:
  - gem install bundler
cache: bundler
sudo: false
dist: xenial
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script: bundle exec rake test
branches:
  only:
  - next
  - gh-pages
  - add-iOS
  - travis-fix
